/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 108
#define YY_END_OF_BUFFER 109
static yyconst short int yy_accept[594] =
    {   0,
        0,    0,    0,    0,  109,  107,  105,  104,  107,  107,
      107,  102,    4,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
        2,  105,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  105,    0,  103,    0,  102,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   85,    0,    0,    3,    0,    2,  105,    0,
        0,    0,    0,    0,    0,    0,    2,    0,  106,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   72,    0,    0,   67,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   65,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   17,    0,    0,
        0,    0,    0,   40,    0,    0,    0,    6,    0,    0,
       42,    0,    0,    0,   33,    0,    0,    0,   36,   32,
        0,    0,    0,   16,    0,    0,  101,    0,    0,    0,
        0,    0,    0,    0,   91,    0,    0,    0,    0,    0,

       86,   89,   51,    0,    0,    0,    0,    0,    0,   60,
        0,    0,    0,    0,    0,   92,    0,    0,    0,    0,
        0,   55,    0,    0,    0,   45,    0,    0,    0,    0,
        0,    0,    0,    0,   88,    0,    0,    0,   53,   12,
        0,    0,   25,    0,    0,    0,    0,    0,    0,   10,
        0,    0,    0,    0,    8,    0,    0,    0,    7,    0,
        0,    0,    0,    0,    0,   27,    0,    0,    0,   59,
       84,    0,   78,    0,    0,    0,    0,   74,    0,    0,
        0,    0,   87,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   50,    0,    0,

        0,   58,    0,   64,    0,    0,    0,   52,    0,    0,
       68,    0,    0,   30,   43,    0,    0,    0,    0,    0,
        0,    0,   26,    0,    0,    0,    0,    0,   13,   28,
        0,   21,    0,    0,    0,   77,    0,   66,   49,   62,
       46,    0,   95,    0,   69,    0,    0,    0,    0,    0,
       47,    0,    0,    0,    0,    0,    0,   48,   99,    0,
       56,    0,   54,    0,    0,   83,    0,    0,    1,    0,
        0,    0,    0,    0,    0,    0,    0,    5,   15,    0,
        0,    0,   37,    0,   20,   93,    0,   90,    0,    0,
        0,   76,    0,    0,    0,    0,   57,   73,   71,    0,

        0,   82,    0,    0,    0,    0,   39,    0,    0,   31,
       11,    9,   19,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   81,    0,   75,
        0,   94,   70,   14,    0,   41,    0,    0,    0,    0,
        0,    0,    0,   96,   61,    0,   98,   44,   79,   80,
        0,    0,   18,    0,    0,    0,    0,    0,    0,    0,
       63,   97,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   34,   35,    0,    0,    0,    0,    0,  100,    0,
        0,    0,   24,    0,    0,    0,   22,    0,    0,   23,
       29,   38,    0

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    1,    7,    1,    8,    1,
        1,    1,    9,    1,   10,   11,    1,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   13,    1,    1,
        1,    1,    1,    1,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
        1,   30,   31,   32,   33,   34,   35,    1,   36,   37,
       38,   11,   39,    1,   40,    1,   41,   42,   43,   44,

       45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
       55,   56,    1,   57,   58,   59,   60,   61,   62,    1,
        1,    1,   11,   11,   11,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[63] =
    {   0,
        1,    2,    3,    2,    1,    2,    1,    1,    2,    2,
        2,    1,    1,    2,    2,    2,    1,    1,    1,    1,
        2,    2,    1,    2,    2,    1,    1,    1,    2,    1,
        2,    1,    1,    1,    2,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1
    } ;

static yyconst short int yy_base[598] =
    {   0,
        0,   57,   81,   60,  702,  703,   63,  703,  696,    0,
      688,  687,  703,  673,  667,   43,   40,  669,   44,   60,
      668,   59,   61,   66,  679,  665,   86,   76,   63,  678,
       70,   49,   63,   74,   70,   83,   72,   76,   87,   98,
       88,   85,   95,  103,  107,   94,  100,  646,  687,  132,
      703,  155,  161,  163,  165,  167,  170,  662,  174,  178,
      150,  161,  170,  199,  183,  683,  703,  679,  674,  653,
      670,  669,  177,  654,  667,  660,  665,  645,  649,  651,
      653,  657,  639,  635,  640,  643,  643,  173,  645,  188,
      640,  646,  637,  637,  649,  647,  636,  646,  634,  207,

      167,   86,  606,  616,  611,  596,  599,  596,  598,  610,
      595,  595,  591,  585,  588,  587,  597,  591,  590,  160,
      583,  578,  176,  580,  595,  180,  580,  582,  575,  188,
      584,  588,  591,  590,  576,  582,  574,  170,  567,  570,
      565,  197,  703,  566,  620,  703,  202,  703,  248,  251,
      253,  230,  240,  244,  245,  250,  703,    0,  703,  608,
      594,  593,  587,  588,  587,  581,  585,  594,  586,  586,
      594,  578,  592,  590,  589,  575,  574,  586,  589,  562,
      583,  575,  567,  581,  575,  570,  571,  572,  563,  574,
      562,  565,  232,  542,  547,  542,  535,  527,  525,  532,

      528,  522,  525,  521,  519,  519,  522,  516,  515,  516,
      514,  519,  524,  525,  509,  703,  508,  509,  703,  514,
      519,  508,  520,  510,  502,  500,  506,  502,  503,  510,
      495,  508,  507,  497,  507,  506,  504,  499,  503,  488,
      495,  484,  703,  497,  481,  491,  490,  479,  534,  251,
      510,  252,  505,  518,  517,  518,  509,  703,  515,  515,
      497,  495,  508,  703,  485,  506,  498,  487,  507,  488,
      703,  490,  250,  502,  703,  503,  488,  487,  703,  703,
      484,  485,  483,  703,  489,  234,  703,  456,  452,  463,
      462,  448,  450,  459,  703,  458,  444,  456,  459,  454,

      703,  703,  703,  457,  452,  451,  485,  448,  444,  703,
      447,  446,  449,  435,  438,  703,  428,  429,  436,  429,
      442,  703,  434,  429,  437,  703,  434,  433,  422,  417,
      416,  415,  419,  424,  703,  414,  418,  410,  703,  703,
      454,  262,  703,  446,  448,  443,  447,  433,  428,  703,
      447,  428,  433,  428,  703,  443,  436,  437,  703,  432,
      439,  420,  426,  424,  422,  703,  420,  419,  427,  703,
      703,  389,  703,  399,  390,  388,  384,  703,  396,  390,
      394,  376,  703,  392,  229,  383,  382,  386,  388,  372,
      372,  384,  383,  386,  379,  368,  368,  703,  378,  363,

      375,  703,  367,  703,  359,  360,  372,  703,  358,  363,
      703,  385,  269,  703,  703,  386,  384,  389,  388,  387,
      378,  393,  703,  381,  387,  374,  383,  371,  703,  703,
      361,  703,  374,  369,  362,  703,  353,  703,  703,  703,
      703,  342,  703,  350,  703,  349,  344,  337,  346,  341,
      703,  329,  329,  344,  329,  333,  330,  703,  703,  327,
      703,  322,  703,  328,  331,  703,  334,  333,  703,  359,
      346,  358,  347,  346,  336,  342,  346,  703,  703,  349,
      337,  266,  703,  335,  703,  703,  321,  703,  319,  317,
      308,  703,  307,  304,  315,  300,  703,  703,  703,  303,

      305,  703,  309,  311,  310,  323,  703,  332,  331,  703,
      703,  703,  703,  336,  314,  320,  319,  331,  320,  304,
      299,  283,  293,  283,  285,  293,  280,  703,  279,  703,
      287,  703,  703,  703,  316,  703,  318,  318,  301,  303,
      306,  314,  297,  703,  703,  267,  703,  703,  703,  703,
      266,  265,  703,  298,  297,  291,  289,  301,  302,  299,
      703,  703,  271,  297,  289,  291,  280,  295,  292,  289,
      264,  703,  703,  290,  288,  261,  260,  268,  703,  261,
      244,  215,  703,  178,  165,  155,  703,  134,   45,  703,
      703,  703,  703,  295,  298,  300,  302

    } ;

static yyconst short int yy_def[598] =
    {   0,
      593,    1,    1,    3,  593,  593,  593,  593,  594,  595,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  596,  593,
      593,  597,  597,  597,  597,  597,  597,  593,  597,  597,
       57,   57,   60,  596,  593,  594,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,

      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  596,  593,  593,  593,  597,  597,
      597,   60,  593,   60,   60,   60,  593,   64,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,

      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,   60,
      593,   60,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,

      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,   60,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,

      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,   60,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,

      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,    0,  593,  593,  593,  593

    } ;

static yyconst short int yy_nxt[766] =
    {   0,
        6,    7,    8,    7,    9,    6,    6,   10,   11,   11,
        6,   12,   13,   14,   15,   16,   17,   18,   19,   20,
        6,   21,    6,    6,   22,   23,   24,   25,   26,   27,
       28,   29,    6,    6,   30,    6,    6,   31,    6,    6,
       32,   33,   34,   35,   36,   37,    6,   38,    6,    6,
        6,   39,   40,   41,   42,   43,   44,   45,   46,   47,
        6,   48,   49,   72,   65,   64,   65,   74,   77,   75,
       73,   78,   82,  100,   84,  592,   83,   79,   85,   87,
       97,  101,   50,   51,   52,   50,   53,   80,   86,   54,
       54,   53,   98,   88,   55,   56,   57,   94,   58,   91,

      102,   53,   59,   92,   53,   60,  103,   95,   96,   61,
      104,   62,  118,   93,  105,   63,  120,  106,  109,  107,
      119,  110,  108,  116,  114,  111,  131,  122,  112,  115,
      121,  123,  129,  113,  194,  124,  117,  126,  127,  133,
      132,  125,  130,  135,  195,  147,  134,  137,  140,   85,
      141,  136,  128,  142,  138,  143,   65,  148,  149,   86,
      591,  139,  593,  148,  593,  148,  593,  148,  593,  148,
      150,  593,  148,  193,   69,  593,  148,   90,  101,  593,
      148,  150,  155,  156,   65,  590,   65,  593,  593,  151,
      152,  154,   95,   96,  589,   83,   71,   73,  179,  180,

       81,  157,  158,  163,  158,  588,  164,  158,  158,  158,
      100,  213,  158,  158,  158,  182,  214,  183,  101,  158,
      158,  217,  158,  158,  240,  221,  241,  158,  227,  158,
      249,  228,  222,  158,  223,  286,  218,  286,  175,  245,
      229,  230,  246,  250,  231,  587,  232,  593,  247,   65,
      148,  149,  593,  148,  593,  148,  251,  150,  150,  167,
      173,  593,  593,  150,  150,  150,  360,  593,  593,  593,
      287,  187,  287,  586,  252,  150,  342,  255,  361,  593,
      446,  516,  150,  413,  160,  447,  593,  435,  585,  584,
      583,  517,  582,  518,  519,   66,   66,   66,   68,   68,

      145,  145,  145,  150,  150,  581,  580,  579,  578,  577,
      576,  575,  574,  573,  572,  571,  570,  569,  568,  567,
      566,  565,  564,  563,  562,  561,  560,  559,  558,  557,
      556,  555,  554,  553,  552,  551,  550,  549,  548,  547,
      546,  545,  544,  543,  542,  541,  540,  539,  538,  537,
      536,  535,  534,  533,  532,  531,  530,  529,  528,  527,
      526,  525,  524,  523,  522,  521,  520,  515,  514,  513,
      512,  511,  510,  509,  508,  507,  506,  505,  504,  503,
      502,  501,  500,  499,  498,  497,  496,  495,  494,  493,
      492,  491,  490,  489,  488,  487,  486,  485,  484,  483,

      482,  481,  480,  479,  478,  477,  476,  475,  474,  473,
      472,  471,  470,  469,  468,  467,  466,  465,  464,  463,
      462,  461,  460,  459,  458,  457,  456,  455,  454,  453,
      452,  451,  450,  449,  448,  445,  444,  443,  442,  441,
      440,  439,  438,  437,  436,  435,  434,  433,  432,  431,
      430,  429,  428,  427,  426,  425,  424,  423,  422,  421,
      420,  419,  418,  417,  416,  415,  414,  412,  411,  410,
      409,  408,  407,  406,  405,  404,  403,  402,  401,  400,
      399,  398,  397,  396,  395,  394,  393,  392,  391,  390,
      389,  388,  387,  386,  385,  384,  383,  382,  381,  380,

      379,  378,  377,  376,  375,  374,  373,  372,  371,  370,
      369,  368,  367,  366,  365,  364,  363,  362,  359,  358,
      357,  356,  355,  354,  353,  352,  351,  350,  349,  348,
      347,  346,  345,  344,  343,  341,  340,  339,  338,  337,
      336,  335,  334,  333,  332,  331,  330,  329,  328,  327,
      326,  325,  324,  323,  322,  321,  320,  319,  318,  317,
      316,  315,  314,  313,  312,  311,  310,  309,  308,  307,
      306,  305,  304,  303,  302,  301,  300,  299,  298,  297,
      296,  295,  294,  293,  292,  291,  290,  289,  288,  285,
      284,  283,  282,  281,  280,  279,  278,  277,  276,  275,

      274,  273,  272,  271,  270,  269,  268,  267,  266,  265,
      264,  263,  262,  261,  260,  259,  258,  257,  256,  255,
      254,  253,  146,  248,  244,  243,  242,  239,  238,  237,
      236,  235,  234,  233,  226,  225,  224,  220,  219,  216,
      215,  212,  211,  210,  209,  208,  207,  206,  205,  204,
      203,  202,  201,  200,  199,  198,  197,  196,  192,  191,
      190,  189,  188,  187,  186,  185,  184,  181,  178,  177,
      176,  175,  174,  173,  172,  171,  170,  169,  168,  167,
      166,  165,  162,  161,  160,   69,  159,   67,  153,  146,
      144,   99,   90,   89,   81,   76,   71,   70,   69,   69,

       67,  593,    5,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593
    } ;

static yyconst short int yy_chk[766] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    2,   16,    7,    4,    7,   17,   19,   17,
       16,   19,   22,   31,   23,  589,   22,   20,   23,   24,
       29,   31,    2,    3,    3,    4,    3,   20,   23,    3,
        3,    3,   29,   24,    3,    3,    3,   28,    3,   27,

       32,    3,    3,   27,    3,    3,   32,   28,   28,    3,
       32,    3,   37,   27,   33,    3,   38,   33,   34,   33,
       37,   34,   33,   36,   35,   34,   42,   39,   34,   35,
       38,   39,   41,   34,  102,   39,   36,   40,   40,   43,
       42,   39,   41,   44,  102,   50,   43,   45,   46,   50,
       46,   44,   40,   47,   45,   47,   52,   52,   52,   50,
      588,   45,   53,   53,   54,   54,   55,   55,   56,   56,
       61,   57,   57,  101,   54,   59,   59,   61,  101,   60,
       60,   62,   62,   63,   65,  586,   65,   63,   62,   55,
       57,   60,   62,   62,  585,   60,   56,   57,   88,   88,

       59,   64,   64,   73,   64,  584,   73,   64,   64,   64,
      100,  120,   64,   64,   64,   90,  120,   90,  100,   64,
       64,  123,   64,   64,  138,  126,  138,   64,  130,   64,
      147,  130,  126,   64,  126,  193,  123,  286,  147,  142,
      130,  130,  142,  152,  130,  582,  130,  152,  142,  149,
      149,  149,  150,  150,  151,  151,  153,  154,  155,  153,
      154,  154,  155,  156,  250,  252,  273,  156,  250,  252,
      193,  155,  286,  581,  156,  342,  252,  250,  273,  342,
      385,  482,  413,  342,  151,  385,  413,  413,  580,  578,
      577,  482,  576,  482,  482,  594,  594,  594,  595,  595,

      596,  596,  596,  597,  597,  575,  574,  571,  570,  569,
      568,  567,  566,  565,  564,  563,  560,  559,  558,  557,
      556,  555,  554,  552,  551,  546,  543,  542,  541,  540,
      539,  538,  537,  535,  531,  529,  527,  526,  525,  524,
      523,  522,  521,  520,  519,  518,  517,  516,  515,  514,
      509,  508,  506,  505,  504,  503,  501,  500,  496,  495,
      494,  493,  491,  490,  489,  487,  484,  481,  480,  477,
      476,  475,  474,  473,  472,  471,  470,  468,  467,  465,
      464,  462,  460,  457,  456,  455,  454,  453,  452,  450,
      449,  448,  447,  446,  444,  442,  437,  435,  434,  433,

      431,  428,  427,  426,  425,  424,  422,  421,  420,  419,
      418,  417,  416,  412,  410,  409,  407,  406,  405,  403,
      401,  400,  399,  397,  396,  395,  394,  393,  392,  391,
      390,  389,  388,  387,  386,  384,  382,  381,  380,  379,
      377,  376,  375,  374,  372,  369,  368,  367,  365,  364,
      363,  362,  361,  360,  358,  357,  356,  354,  353,  352,
      351,  349,  348,  347,  346,  345,  344,  341,  338,  337,
      336,  334,  333,  332,  331,  330,  329,  328,  327,  325,
      324,  323,  321,  320,  319,  318,  317,  315,  314,  313,
      312,  311,  309,  308,  307,  306,  305,  304,  300,  299,

      298,  297,  296,  294,  293,  292,  291,  290,  289,  288,
      285,  283,  282,  281,  278,  277,  276,  274,  272,  270,
      269,  268,  267,  266,  265,  263,  262,  261,  260,  259,
      257,  256,  255,  254,  253,  251,  249,  248,  247,  246,
      245,  244,  242,  241,  240,  239,  238,  237,  236,  235,
      234,  233,  232,  231,  230,  229,  228,  227,  226,  225,
      224,  223,  222,  221,  220,  218,  217,  215,  214,  213,
      212,  211,  210,  209,  208,  207,  206,  205,  204,  203,
      202,  201,  200,  199,  198,  197,  196,  195,  194,  192,
      191,  190,  189,  188,  187,  186,  185,  184,  183,  182,

      181,  180,  179,  178,  177,  176,  175,  174,  173,  172,
      171,  170,  169,  168,  167,  166,  165,  164,  163,  162,
      161,  160,  145,  144,  141,  140,  139,  137,  136,  135,
      134,  133,  132,  131,  129,  128,  127,  125,  124,  122,
      121,  119,  118,  117,  116,  115,  114,  113,  112,  111,
      110,  109,  108,  107,  106,  105,  104,  103,   99,   98,
       97,   96,   95,   94,   93,   92,   91,   89,   87,   86,
       85,   84,   83,   82,   81,   80,   79,   78,   77,   76,
       75,   74,   72,   71,   70,   69,   68,   66,   58,   49,
       48,   30,   26,   25,   21,   18,   15,   14,   12,   11,

        9,    5,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593,  593,  593,  593,  593,  593,
      593,  593,  593,  593,  593
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "..\\..\\util\\lev_comp.l"
#define INITIAL 0
#line 2 "..\\..\\util\\lev_comp.l"
/*	SCCS Id: @(#)lev_lex.c	3.2	96/05/16	*/
/*	Copyright (c) 1989 by Jean-Christophe Collet */
/* NetHack may be freely redistributed.  See license for details. */

#define LEV_LEX_C

#include "hack.h"
#include "lev_comp.h"
#include "sp_lev.h"

/* Most of these don't exist in flex, yywrap is macro and
 * yyunput is properly declared in flex.skel.
 */
#if !defined(FLEX_SCANNER) && !defined(FLEXHACK_SCANNER)
int FDECL(yyback, (int *,int));
int NDECL(yylook);
int NDECL(yyinput);
int NDECL(yywrap);
int NDECL(yylex);
	/* Traditional lexes let yyunput() and yyoutput() default to int;
	 * newer ones may declare them as void since they don't return
	 * values.  For even more fun, the lex supplied as part of the
	 * newer unbundled compiler for SunOS 4.x adds the void declarations
	 * (under __STDC__ or _cplusplus ifdefs -- otherwise they remain
	 * int) while the bundled lex and the one with the older unbundled
	 * compiler do not.  To detect this, we need help from outside --
	 * sys/unix/Makefile.utl.
	 */
# if defined(NeXT) || defined(SVR4) || defined(_AIX32)
#  define VOIDYYPUT
# endif
# if !defined(VOIDYYPUT)
#  if defined(POSIX_TYPES) && !defined(BOS) && !defined(HISX) && !defined(_M_UNIX) && !defined(VMS)
#   define VOIDYYPUT
#  endif
# endif
# if !defined(VOIDYYPUT) && defined(WEIRD_LEX)
#  if defined(SUNOS4) && defined(__STDC__) && (WEIRD_LEX > 1)
#   define VOIDYYPUT
#  endif
# endif
# ifdef VOIDYYPUT
void FDECL(yyunput, (int));
void FDECL(yyoutput, (int));
# else
int FDECL(yyunput, (int));
int FDECL(yyoutput, (int));
# endif
#endif	/* !FLEX_SCANNER && !FLEXHACK_SCANNER */

#ifdef FLEX_SCANNER
#define YY_MALLOC_DECL \
	      genericptr_t FDECL(malloc, (size_t)); \
	      genericptr_t FDECL(realloc, (genericptr_t,size_t));
#endif

void FDECL(init_yyin, (FILE *));
void FDECL(init_yyout, (FILE *));

/*
 * This doesn't always get put in lev_comp.h
 * (esp. when using older versions of bison).
 */
extern YYSTYPE yylval;

int line_number = 1, colon_line_number = 1;
static char map[4096];
static int map_cnt = 0;

/*
 *	This is a hack required by Michael Hamel to get things
 *	working on the Mac.
 */
#if defined(applec) && !defined(FLEX_SCANNER) && !defined(FLEXHACK_SCANNER)
#undef input
#undef unput
#define unput(c) { yytchar = (c); if (yytchar == 10) yylineno--; *yysptr++ = yytchar; }
# ifndef YYNEWLINE
# define YYNEWLINE 10
# endif

char
input()		/* Under MPW \n is chr(13)! Compensate for this. */
{
	if (yysptr > yysbuf) return(*--yysptr);
	else {
		yytchar = getc(yyin);
		if (yytchar == '\n') {
		    yylineno++;
		    return(YYNEWLINE);
		}
		if (yytchar == EOF) return(0);
		else		    return(yytchar);
	}
}
#endif	/* applec && !FLEX_SCANNER && !FLEXHACK_SCANNER */

#define MAPC 1

#line 835 "lexyy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 111 "..\\..\\util\\lev_comp.l"

#line 987 "lexyy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 594 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 703 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 112 "..\\..\\util\\lev_comp.l"
{
		  BEGIN(INITIAL);
		  yylval.map = (char *) alloc(map_cnt + 1);
		  (void) strncpy(yylval.map, map, map_cnt);
		  yylval.map[map_cnt] = 0;
		  map_cnt = 0;
		  return MAP_ID;
		}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 120 "..\\..\\util\\lev_comp.l"
{
		  line_number++;
		  (void) strncpy(map + map_cnt, yytext, yyleng);
		  map_cnt += yyleng;
		  map[map_cnt] = 0;
		}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 126 "..\\..\\util\\lev_comp.l"
{ line_number++; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 127 "..\\..\\util\\lev_comp.l"
{ colon_line_number = line_number; return ':'; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 128 "..\\..\\util\\lev_comp.l"
return MESSAGE_ID;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 129 "..\\..\\util\\lev_comp.l"
return MAZE_ID;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 130 "..\\..\\util\\lev_comp.l"
return NOMAP_ID;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 131 "..\\..\\util\\lev_comp.l"
return LEVEL_ID;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 132 "..\\..\\util\\lev_comp.l"
return LEV_INIT_ID;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 133 "..\\..\\util\\lev_comp.l"
return FLAGS_ID;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 134 "..\\..\\util\\lev_comp.l"
return GEOMETRY_ID;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 135 "..\\..\\util\\lev_comp.l"
{ BEGIN(MAPC); line_number++; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 136 "..\\..\\util\\lev_comp.l"
return OBJECT_ID;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 137 "..\\..\\util\\lev_comp.l"
return COBJECT_ID;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 138 "..\\..\\util\\lev_comp.l"
return MONSTER_ID;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 139 "..\\..\\util\\lev_comp.l"
return TRAP_ID;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 140 "..\\..\\util\\lev_comp.l"
return DOOR_ID;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 141 "..\\..\\util\\lev_comp.l"
return DRAWBRIDGE_ID;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 142 "..\\..\\util\\lev_comp.l"
return MAZEWALK_ID;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 143 "..\\..\\util\\lev_comp.l"
return WALLIFY_ID;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 144 "..\\..\\util\\lev_comp.l"
return REGION_ID;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 145 "..\\..\\util\\lev_comp.l"
return RANDOM_OBJECTS_ID;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 146 "..\\..\\util\\lev_comp.l"
return RANDOM_MONSTERS_ID;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 147 "..\\..\\util\\lev_comp.l"
return RANDOM_PLACES_ID;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 148 "..\\..\\util\\lev_comp.l"
return ALTAR_ID;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 149 "..\\..\\util\\lev_comp.l"
return LADDER_ID;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 150 "..\\..\\util\\lev_comp.l"
return STAIR_ID;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 151 "..\\..\\util\\lev_comp.l"
return PORTAL_ID;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 152 "..\\..\\util\\lev_comp.l"
return TELEPRT_ID;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 153 "..\\..\\util\\lev_comp.l"
return BRANCH_ID;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 154 "..\\..\\util\\lev_comp.l"
return FOUNTAIN_ID;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 155 "..\\..\\util\\lev_comp.l"
return SINK_ID;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 156 "..\\..\\util\\lev_comp.l"
return POOL_ID;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 157 "..\\..\\util\\lev_comp.l"
return NON_DIGGABLE_ID;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 158 "..\\..\\util\\lev_comp.l"
return NON_PASSWALL_ID;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 159 "..\\..\\util\\lev_comp.l"
return ROOM_ID;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 160 "..\\..\\util\\lev_comp.l"
return SUBROOM_ID;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 161 "..\\..\\util\\lev_comp.l"
return RAND_CORRIDOR_ID;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 162 "..\\..\\util\\lev_comp.l"
return CORRIDOR_ID;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 163 "..\\..\\util\\lev_comp.l"
return GOLD_ID;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 164 "..\\..\\util\\lev_comp.l"
return ENGRAVING_ID;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 165 "..\\..\\util\\lev_comp.l"
return NAME_ID;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 166 "..\\..\\util\\lev_comp.l"
return CHANCE_ID;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 167 "..\\..\\util\\lev_comp.l"
return LEV;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 168 "..\\..\\util\\lev_comp.l"
{ yylval.i=D_ISOPEN; return DOOR_STATE; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 169 "..\\..\\util\\lev_comp.l"
{ yylval.i=D_CLOSED; return DOOR_STATE; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 170 "..\\..\\util\\lev_comp.l"
{ yylval.i=D_LOCKED; return DOOR_STATE; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 171 "..\\..\\util\\lev_comp.l"
{ yylval.i=D_NODOOR; return DOOR_STATE; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 172 "..\\..\\util\\lev_comp.l"
{ yylval.i=D_BROKEN; return DOOR_STATE; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 173 "..\\..\\util\\lev_comp.l"
{ yylval.i=W_NORTH; return DIRECTION; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 174 "..\\..\\util\\lev_comp.l"
{ yylval.i=W_EAST; return DIRECTION; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 175 "..\\..\\util\\lev_comp.l"
{ yylval.i=W_SOUTH; return DIRECTION; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 176 "..\\..\\util\\lev_comp.l"
{ yylval.i=W_WEST; return DIRECTION; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 177 "..\\..\\util\\lev_comp.l"
{ yylval.i = -1; return RANDOM_TYPE; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 178 "..\\..\\util\\lev_comp.l"
{ yylval.i = -2; return NONE; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 179 "..\\..\\util\\lev_comp.l"
return O_REGISTER;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 180 "..\\..\\util\\lev_comp.l"
return M_REGISTER;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 181 "..\\..\\util\\lev_comp.l"
return P_REGISTER;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 182 "..\\..\\util\\lev_comp.l"
return A_REGISTER;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 183 "..\\..\\util\\lev_comp.l"
{ yylval.i=1; return LEFT_OR_RIGHT; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 184 "..\\..\\util\\lev_comp.l"
{ yylval.i=2; return LEFT_OR_RIGHT; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 185 "..\\..\\util\\lev_comp.l"
{ yylval.i=3; return CENTER; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 186 "..\\..\\util\\lev_comp.l"
{ yylval.i=4; return LEFT_OR_RIGHT; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 187 "..\\..\\util\\lev_comp.l"
{ yylval.i=5; return LEFT_OR_RIGHT; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 188 "..\\..\\util\\lev_comp.l"
{ yylval.i=1; return TOP_OR_BOT; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 189 "..\\..\\util\\lev_comp.l"
{ yylval.i=5; return TOP_OR_BOT; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 190 "..\\..\\util\\lev_comp.l"
{ yylval.i=1; return LIGHT_STATE; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 191 "..\\..\\util\\lev_comp.l"
{ yylval.i=0; return LIGHT_STATE; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 192 "..\\..\\util\\lev_comp.l"
{ yylval.i=0; return FILLING; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 193 "..\\..\\util\\lev_comp.l"
{ yylval.i=1; return FILLING; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 194 "..\\..\\util\\lev_comp.l"
{ yylval.i= AM_NONE; return ALIGNMENT; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 195 "..\\..\\util\\lev_comp.l"
{ yylval.i= AM_LAWFUL; return ALIGNMENT; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 196 "..\\..\\util\\lev_comp.l"
{ yylval.i= AM_NEUTRAL; return ALIGNMENT; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 197 "..\\..\\util\\lev_comp.l"
{ yylval.i= AM_CHAOTIC; return ALIGNMENT; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 198 "..\\..\\util\\lev_comp.l"
{ yylval.i=1; return MON_ATTITUDE; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 199 "..\\..\\util\\lev_comp.l"
{ yylval.i=0; return MON_ATTITUDE; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 200 "..\\..\\util\\lev_comp.l"
{ yylval.i=1; return MON_ALERTNESS; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 201 "..\\..\\util\\lev_comp.l"
{ yylval.i=0; return MON_ALERTNESS; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 202 "..\\..\\util\\lev_comp.l"
{ yylval.i= M_AP_FURNITURE; return MON_APPEARANCE; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 203 "..\\..\\util\\lev_comp.l"
{ yylval.i= M_AP_MONSTER;   return MON_APPEARANCE; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 204 "..\\..\\util\\lev_comp.l"
{ yylval.i= M_AP_OBJECT;    return MON_APPEARANCE; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 205 "..\\..\\util\\lev_comp.l"
{ yylval.i=2; return ALTAR_TYPE; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 206 "..\\..\\util\\lev_comp.l"
{ yylval.i=1; return ALTAR_TYPE; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 207 "..\\..\\util\\lev_comp.l"
{ yylval.i=0; return ALTAR_TYPE; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 208 "..\\..\\util\\lev_comp.l"
{ yylval.i=1; return UP_OR_DOWN; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 209 "..\\..\\util\\lev_comp.l"
{ yylval.i=0; return UP_OR_DOWN; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 210 "..\\..\\util\\lev_comp.l"
{ yylval.i=0; return BOOLEAN; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 211 "..\\..\\util\\lev_comp.l"
{ yylval.i=1; return BOOLEAN; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 212 "..\\..\\util\\lev_comp.l"
{ yylval.i=DUST; return ENGRAVING_TYPE; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 213 "..\\..\\util\\lev_comp.l"
{ yylval.i=ENGRAVE; return ENGRAVING_TYPE; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 214 "..\\..\\util\\lev_comp.l"
{ yylval.i=BURN; return ENGRAVING_TYPE; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 215 "..\\..\\util\\lev_comp.l"
{ yylval.i=MARK; return ENGRAVING_TYPE; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 216 "..\\..\\util\\lev_comp.l"
{ yylval.i=1; return CURSE_TYPE; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 217 "..\\..\\util\\lev_comp.l"
{ yylval.i=2; return CURSE_TYPE; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 218 "..\\..\\util\\lev_comp.l"
{ yylval.i=3; return CURSE_TYPE; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 219 "..\\..\\util\\lev_comp.l"
{ return CONTAINED; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 220 "..\\..\\util\\lev_comp.l"
{ yylval.i=NOTELEPORT; return FLAG_TYPE; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 221 "..\\..\\util\\lev_comp.l"
{ yylval.i=HARDFLOOR; return FLAG_TYPE; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 222 "..\\..\\util\\lev_comp.l"
{ yylval.i=NOMMAP; return FLAG_TYPE; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 223 "..\\..\\util\\lev_comp.l"
{ yylval.i=SHORTSIGHTED; return FLAG_TYPE; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 224 "..\\..\\util\\lev_comp.l"
{ yylval.i = atoi(yytext + 1); return PERCENT; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 225 "..\\..\\util\\lev_comp.l"
{ yylval.i=atoi(yytext); return INTEGER; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 226 "..\\..\\util\\lev_comp.l"
{ yytext[yyleng-1] = 0; /* Discard the trailing \" */
		  yylval.map = (char *) alloc(strlen(yytext+1)+1);
		  Strcpy(yylval.map, yytext+1); /* Discard the first \" */
		  return STRING; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 230 "..\\..\\util\\lev_comp.l"
{ line_number++; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 231 "..\\..\\util\\lev_comp.l"
;
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 232 "..\\..\\util\\lev_comp.l"
{ yylval.i = yytext[1]; return CHAR; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 233 "..\\..\\util\\lev_comp.l"
{ return yytext[0]; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 234 "..\\..\\util\\lev_comp.l"
ECHO;
	YY_BREAK
#line 1626 "lexyy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(MAPC):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 594 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 594 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 593);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 234 "..\\..\\util\\lev_comp.l"

#ifdef	AMIGA
long *alloc(n)
	unsigned n;
{
	return ((long *)malloc (n));
}
#endif

/* routine to switch to another input file; needed for flex */
void init_yyin( input_f )
FILE *input_f;
{
#if defined(FLEX_SCANNER) || defined(FLEXHACK_SCANNER)
	if (yyin)
	    yyrestart(input_f);
	else
#endif
	    yyin = input_f;
}
/* analogous routine (for completeness) */
void init_yyout( output_f )
FILE *output_f;
{
	yyout = output_f;
}

/*lev_comp.l*/
