#	NetHack Makefile.
#	SCCS Id: @(#)Makefile.dat	3.1	92/09/18

# by issei 1994/2/5
#VARDAT = data rumors quest.dat oracles options
VARDAT = data jrumors quest.dat joracles options

all:	$(VARDAT) spec_levs quest_levs dungeon

../util/makedefs:
	(cd ../util ; make makedefs)

../util/dgn_comp:
	(cd ../util ; make dgn_comp)

../util/lev_comp:
	(cd ../util ; make lev_comp)

../util/tile2x11:
	(cd ../util ; make tile2x11)

x11tiles: ../util/tile2x11 ../win/share/monsters.txt ../win/share/objects.txt \
				../win/share/other.txt
	../util/tile2x11 ../win/share/monsters.txt ../win/share/objects.txt \
				../win/share/other.txt

pet_mark.xbm: ../win/X11/pet_mark.xbm
	cp ../win/X11/pet_mark.xbm pet_mark.xbm

rip.xpm: ../win/X11/rip.xpm
	cp ../win/X11/rip.xpm rip.xpm

data:	data.base ../util/makedefs
	../util/makedefs -d

#rumors:	rumors.tru rumors.fal ../util/makedefs
jrumors:	jrumors.tru jrumors.fal ../util/makedefs
	../util/makedefs -r

quest.dat:	quest.txt ../util/makedefs
	../util/makedefs -q

# by issei 1994/2/5
#oracles:	oracles.txt ../util/makedefs
joracles:	joracles.txt ../util/makedefs
	../util/makedefs -h

# note: 'options' should have already been made when include/date.h was created
options:	../util/makedefs
	../util/makedefs -v


spec_levs: ../util/lev_comp \
	bigroom.des castle.des endgame.des gehennom.des knox.des medusa.des \
	mines.des oracle.des tower.des yendor.des \
	beholder.des caves.des darkelf.des dragons.des giants.des guild.des \
	kobold-1.des kobold-2.des lich.des mall-1.des mall-2.des \
	mtemple.des newmall.des nymph.des rats.des sea.des \
	spiders.des stor-1.des stor-2.des stor-3.des tomb.des
	../util/lev_comp bigroom.des
	../util/lev_comp blkmar.des
	../util/lev_comp castle.des
	../util/lev_comp endgame.des
	../util/lev_comp gehennom.des
	../util/lev_comp knox.des
	../util/lev_comp medusa.des
	../util/lev_comp mines.des
	../util/lev_comp oracle.des
	../util/lev_comp tower.des
	../util/lev_comp yendor.des
	../util/lev_comp beholder.des
	../util/lev_comp caves.des
	../util/lev_comp darkelf.des
	../util/lev_comp dragons.des
	../util/lev_comp giants.des
	../util/lev_comp guild.des
	../util/lev_comp kobold-1.des
	../util/lev_comp kobold-2.des
	../util/lev_comp lich.des
	../util/lev_comp mall-1.des
	../util/lev_comp mall-2.des
	../util/lev_comp mtemple.des
	../util/lev_comp newmall.des
	../util/lev_comp nymph.des
	../util/lev_comp rats.des
	../util/lev_comp sea.des
	../util/lev_comp spiders.des
	../util/lev_comp stor-1.des
	../util/lev_comp stor-2.des
	../util/lev_comp stor-3.des
	../util/lev_comp tomb.des
	touch spec_levs

quest_levs: ../util/lev_comp \
	Arch.des Barb.des Caveman.des Elf.des Healer.des Knight.des \
	Priest.des Rogue.des Samurai.des Tourist.des Valkyrie.des Wizard.des \
	Dopp.des Flame.des Gnome.des Ice.des Lycn.des Monk.des Necro.des \
	Slayer.des Fighter.des
	../util/lev_comp Arch.des
	../util/lev_comp Barb.des
	../util/lev_comp Caveman.des
	../util/lev_comp Elf.des
	../util/lev_comp Healer.des
	../util/lev_comp Knight.des
	../util/lev_comp Priest.des
	../util/lev_comp Rogue.des
	../util/lev_comp Samurai.des
	../util/lev_comp Tourist.des
	../util/lev_comp Valkyrie.des
	../util/lev_comp Wizard.des
	../util/lev_comp Dopp.des
	../util/lev_comp Flame.des
	../util/lev_comp Gnome.des
	../util/lev_comp Ice.des
	../util/lev_comp Lycn.des
	../util/lev_comp Monk.des
	../util/lev_comp Necro.des
	../util/lev_comp Slayer.des
	../util/lev_comp Fighter.des
	touch quest_levs

dungeon: dungeon.def ../util/makedefs ../util/dgn_comp
	../util/makedefs -e
	../util/dgn_comp dungeon.pdf

spotless:
	-rm -f spec_levs quest_levs *.lev $(VARDAT) dungeon dungeon.pdf
