/*	SCCS Id: @(#)date.h	3.2	96/05/17 */

/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Wed Apr 30 13:13:05 2025"
#define BUILD_TIME (1745986385L)

#define VERSION_NUMBER 0x04010208UL
#define VERSION_FEATURES 0x187f04c6UL
#define VERSION_SANITY1 0x441ea234UL
#define VERSION_SANITY2 0x74d22448UL

#define VERSION_ID \
 "Unix NetHack Beta Version 4.1.2-8 - last build Wed Apr 30 13:13:05 2025."
#define JVERSION_ID \
 "Unix JNetHack Beta Version 1.0.5-3 - last build Wed Apr 30 13:13:05 2025."
